name: music_widget_flutter
description: "A new Flutter project."


publish_to: 'none' 













version: 0.9.16+1

environment:
  sdk: ^3.12.2







dependencies:
  flutter:
    sdk: flutter

  
  
  cupertino_icons: ^1.0.8
  window_manager: ^0.5.1
  smtc_windows: ^1.1.0
  tray_manager: ^0.2.3
  shared_preferences: ^2.3.2
  file_picker: ^11.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^6.0.0

  
  msix: ^3.16.2





flutter:

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
dependency_overrides:
  flutter_rust_bridge: 2.11.1

msix_config:
  display_name: MD3MusicWidget
  publisher_display_name: syj
  identity_name: com.fuckyou.md3musicwidget
  logo_path: assets/logo.png 
